

- name: installing and run mysql
  hosts: 172.31.31.171  #172.31.23.112
  become: yes #equal to -b in adhoc command ,getting root accesss
  tasks:
  - name: install mysql
    ansible.builtin.dnf:
      name: mysql
      state: latest
  - name: start mysql
    ansible.builtin.service:
      name: mysql
      state: started
      enabled: yes    
