- name: install and run mysql
  hosts: mysql
  become: yes
  tasks: #install and run mysql
  - name: insatll mysql
    ansible.builtin.dnf:
      name: mysql
      state: latest
  - name: start mysql
    ansible.builtin.service:
       name: mysql
       state: started
       enabled: yes


