- name:  variable
  hosts: localhost
  tasks:
  vars:
    course: "Ansible"
    trainer: "siva"
    Duration: "120hrs"
  tasks:
  - name: print information
    ansible.builtin.debug:
      msg: "Hi, we are learning {{course}} from trainer {{trainer}} ,Devops  {{Duration}}..."
