- name:  variable
  hosts: localhost
  tasks:
  variable:
  course: "Ansible"
  trainer: "siva"
  Duration: "120hrs"
  - name: print information
    ansible.builtin.debug:
      msg: "Hi, we are learning {{course} }Ansible from  {{trainer}} ,Devops duration {{120 hrs}}..."
