- name:  variable
  hosts: localhost
  tasks:
  vars:
    courses: "Ansible"
    trainer: "siva"
    Duration: "120hrs"
  tasks:
  - name: print overried information
    vars: #task level vars
      courses: "Devops"
    ansible.builtin.debug:
      msg: "Hi, we are learning {{courses}} from trainer {{trainer}} ,Devops  {{Duration}}..."


  tasks:
  - name: print without overried information
    ansible.builtin.debug:
      msg: "Hi, we are learning {{courses}} from trainer {{trainer}} ,Devops  {{Duration}}..."
