- name: variables
  hosts: localhost
  vars_files:
  - vars.yaml
  tasks:
  - name:  print variablefrom vars file
    ansible.builtin.debug:
      msg : 'Hi i am learning {{course}} from {{trainer}} with {{Duration}}'