- name: variables
  hosts: localhost
  tasks:
  - name:  print variablefrom vars file
    ansible.builtin.debug:
      msg : 'Hi i am learning {{course}} from {{trainer}} with {{Duration}} also {{Timings}}'