- name: conditions
  hosts: web
  become: yes
  tasks:
  - name: check user exists or not
    ansible.builtin.command: id expense
    register: USER # ID EXPENSE VALUE IS STORES
    innore_error: true

  - name: say Hello
    ansible.builtin.debug:
      msg: "Hello ..."
      msg: "user info :: {{USER}} ..."

  - name: say Hello
     ansible.builtin.debug:
      msg: "Hello ..."  