- name: conditions
  hosts: web
  become: yes
  tasks:
  - name: check user exists or not
    ansible.builtin.command: id expense
    register: USER # ID EXPENSE VALUE IS STORES
    innore_error: true

  - name: print user info
    ansible.builtin.debug:
      msg: "user info :: {{USER}}"
