- name: check number
  hosts: localhost
  vars_prompt: # prompts are always consider as text/string
  - name: number
    prompt: please enter number
    private: no
  tasks:
  - name: number is less then 10
    ansible.builtin.debug:
      msg: "Given number  {{number}} is less then 10"
    when: number | int < 10
  - name: number is greater then or eual to 10
    ansible.builtin.debug:
      msg: "Given number  {{number}} is greater then 10"
    when: number | int >= 10

