
- name: install packages
  hosts: web
  become: yes
  tasks:
  - name: install packages
    ansible.builtin.dnf:
      name: "{{ item.name }}"
      state: "{{ latest.state }}" 
    loop:
    - { name: 'mysql' , state: 'latest'} # item
    - { name: 'nginx' , state: 'absent'}
    - { name: 'postfix' , state: 'absent'}